version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /cicd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /cicd/docker-credentials/password
    DOCKER_REGISTRY_URL: /cicd/docker-registry/url

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing Trivy..."
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

  pre_build:
    commands:
      - echo "Running Trivy filesystem scan..."
      - trivy fs --exit-code 0 --no-progress . > trivyfilescan.txt
      - echo "Logging into Docker..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"

  build:
    commands:
      - echo "Building Docker image..."
      - IMAGE_NAME="$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/swiggy:latest"
      - echo "Image name: $IMAGE_NAME"
      - docker build -t "$IMAGE_NAME" .
      - docker push "$IMAGE_NAME"

  post_build:
    commands:
      - echo "Running Trivy image scan..."
      - trivy image "$IMAGE_NAME" > trivyimage.txt

artifacts:
  files:
    - trivyfilescan.txt
    - trivyimage.txt
